import type { TemplateSlot } from '../types/template';
import { A4_BASE_HEIGHT, A4_BASE_WIDTH } from './templateEditor.ts';

/** Canonical slot geometry; pitch packs overlay patches on this baseline. */
export const LANDING_BASE_SLOTS: TemplateSlot[] = [
  {
    id: 'slot:hero:badge',
    type: 'pill',
    componentKind: 'statChip',
    x: 140,
    y: 76,
    w: 120,
    h: 44,
    maxChars: 16,
    maxLines: 1,
    overflow: 'ellipsis',
  },
  {
    id: 'slot:hero:headline',
    type: 'text',
    x: 140,
    y: 140,
    w: 740,
    h: 148,
    maxChars: 110,
    maxLines: 3,
    overflow: 'wrap',
  },
  {
    id: 'slot:hero:subheadline',
    type: 'text',
    x: 140,
    y: 304,
    w: 740,
    h: 96,
    maxChars: 190,
    maxLines: 3,
    overflow: 'wrap',
  },
  {
    id: 'slot:hero:cta:primary',
    type: 'cta',
    x: 140,
    y: 430,
    w: 188,
    h: 52,
    maxChars: 26,
    maxLines: 1,
    overflow: 'ellipsis',
  },
  {
    id: 'slot:hero:cta:secondary',
    type: 'cta',
    x: 348,
    y: 430,
    w: 188,
    h: 52,
    maxChars: 26,
    maxLines: 1,
    overflow: 'ellipsis',
  },
  { id: 'slot:hero:visual', type: 'box', x: 930, y: 110, w: 520, h: 380 },
  {
    id: 'slot:social:title',
    type: 'text',
    x: 140,
    y: 530,
    w: 420,
    h: 40,
    maxChars: 60,
    maxLines: 1,
    overflow: 'ellipsis',
  },
  { id: 'slot:logo:1', type: 'logo', x: 140, y: 582, w: 160, h: 56, maxChars: 18, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:logo:2', type: 'logo', x: 318, y: 582, w: 160, h: 56, maxChars: 18, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:logo:3', type: 'logo', x: 496, y: 582, w: 160, h: 56, maxChars: 18, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:logo:4', type: 'logo', x: 674, y: 582, w: 160, h: 56, maxChars: 18, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:logo:5', type: 'logo', x: 852, y: 582, w: 160, h: 56, maxChars: 18, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:logo:6', type: 'logo', x: 1030, y: 582, w: 160, h: 56, maxChars: 18, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:steps:pill:1', type: 'pill', x: 140, y: 672, w: 214, h: 54, maxChars: 26, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:steps:pill:2', type: 'pill', x: 444, y: 672, w: 214, h: 54, maxChars: 26, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:steps:pill:3', type: 'pill', x: 748, y: 672, w: 214, h: 54, maxChars: 26, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:steps:connector:1', type: 'connector', x: 356, y: 699, w: 84, h: 4 },
  { id: 'slot:steps:connector:2', type: 'connector', x: 660, y: 699, w: 84, h: 4 },
  {
    id: 'slot:steps:desc:1',
    type: 'text',
    x: 140,
    y: 735,
    w: 214,
    h: 52,
    maxChars: 62,
    maxLines: 2,
    overflow: 'wrap',
  },
  {
    id: 'slot:steps:desc:2',
    type: 'text',
    x: 444,
    y: 735,
    w: 214,
    h: 52,
    maxChars: 62,
    maxLines: 2,
    overflow: 'wrap',
  },
  {
    id: 'slot:steps:desc:3',
    type: 'text',
    x: 748,
    y: 735,
    w: 214,
    h: 52,
    maxChars: 62,
    maxLines: 2,
    overflow: 'wrap',
  },
  { id: 'slot:math:box', type: 'box', x: 990, y: 668, w: 460, h: 168 },
  {
    id: 'slot:math:title',
    type: 'text',
    x: 1030,
    y: 692,
    w: 380,
    h: 34,
    maxChars: 44,
    maxLines: 1,
    overflow: 'ellipsis',
  },
  {
    id: 'slot:math:formula',
    type: 'text',
    x: 1030,
    y: 726,
    w: 380,
    h: 46,
    maxChars: 90,
    maxLines: 2,
    overflow: 'wrap',
  },
  {
    id: 'slot:math:footnote',
    type: 'text',
    x: 1030,
    y: 774,
    w: 380,
    h: 38,
    maxChars: 100,
    maxLines: 2,
    overflow: 'clip',
  },
  {
    id: 'slot:final:headline',
    type: 'text',
    x: 140,
    y: 816,
    w: 760,
    h: 42,
    maxChars: 88,
    maxLines: 1,
    overflow: 'ellipsis',
  },
];

/** landing.v1 — portrait A4 editorial layout. */
export const LANDING_PAGE_PORTRAIT = {
  width: A4_BASE_WIDTH,
  height: A4_BASE_HEIGHT,
} as const;

const LANDING_BASE_SLOTS_PORTRAIT_SOURCE: TemplateSlot[] = [
  {
    id: 'slot:hero:badge',
    type: 'pill',
    componentKind: 'statChip',
    x: 450,
    y: 136,
    w: 340,
    h: 42,
    maxChars: 28,
    maxLines: 1,
    overflow: 'ellipsis',
  },
  {
    id: 'slot:hero:headline',
    type: 'text',
    x: 80,
    y: 194,
    w: 1080,
    h: 210,
    maxChars: 140,
    maxLines: 3,
    overflow: 'wrap',
  },
  {
    id: 'slot:hero:subheadline',
    type: 'text',
    x: 160,
    y: 424,
    w: 920,
    h: 88,
    maxChars: 220,
    maxLines: 3,
    overflow: 'wrap',
  },
  {
    id: 'slot:hero:cta:primary',
    type: 'cta',
    x: 392,
    y: 548,
    w: 220,
    h: 52,
    maxChars: 32,
    maxLines: 1,
    overflow: 'ellipsis',
  },
  {
    id: 'slot:hero:cta:secondary',
    type: 'cta',
    x: 628,
    y: 548,
    w: 220,
    h: 52,
    maxChars: 24,
    maxLines: 1,
    overflow: 'ellipsis',
  },
  { id: 'slot:hero:visual', type: 'box', x: 0, y: 0, w: 0, h: 0 },
  {
    id: 'slot:social:title',
    type: 'text',
    x: 340,
    y: 664,
    w: 560,
    h: 24,
    maxChars: 64,
    maxLines: 1,
    overflow: 'ellipsis',
  },
  { id: 'slot:logo:1', type: 'logo', x: 356, y: 704, w: 160, h: 36, maxChars: 16, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:logo:2', type: 'logo', x: 540, y: 704, w: 160, h: 36, maxChars: 16, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:logo:3', type: 'logo', x: 724, y: 704, w: 160, h: 36, maxChars: 16, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:logo:4', type: 'logo', x: 812, y: 704, w: 160, h: 36, maxChars: 16, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:logo:5', type: 'logo', x: 996, y: 704, w: 160, h: 36, maxChars: 16, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:logo:6', type: 'logo', x: 565, y: 1730, w: 110, h: 20, maxChars: 14, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:steps:pill:1', type: 'pill', x: 80, y: 804, w: 344, h: 54, maxChars: 30, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:steps:pill:2', type: 'pill', x: 448, y: 804, w: 344, h: 54, maxChars: 30, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:steps:pill:3', type: 'pill', x: 816, y: 804, w: 344, h: 54, maxChars: 30, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:steps:connector:1', type: 'connector', x: 424, y: 830, w: 24, h: 2 },
  { id: 'slot:steps:connector:2', type: 'connector', x: 792, y: 830, w: 24, h: 2 },
  {
    id: 'slot:steps:desc:1',
    type: 'text',
    x: 80,
    y: 870,
    w: 344,
    h: 170,
    maxChars: 90,
    maxLines: 4,
    overflow: 'wrap',
  },
  {
    id: 'slot:steps:desc:2',
    type: 'text',
    x: 448,
    y: 870,
    w: 344,
    h: 170,
    maxChars: 90,
    maxLines: 4,
    overflow: 'wrap',
  },
  {
    id: 'slot:steps:desc:3',
    type: 'text',
    x: 816,
    y: 870,
    w: 344,
    h: 170,
    maxChars: 90,
    maxLines: 4,
    overflow: 'wrap',
  },
  { id: 'slot:math:box', type: 'box', x: 80, y: 1104, w: 1080, h: 300 },
  {
    id: 'slot:math:title',
    type: 'text',
    x: 128,
    y: 1152,
    w: 984,
    h: 34,
    maxChars: 56,
    maxLines: 1,
    overflow: 'wrap',
  },
  {
    id: 'slot:math:formula',
    type: 'text',
    x: 128,
    y: 1200,
    w: 984,
    h: 96,
    maxChars: 180,
    maxLines: 4,
    overflow: 'wrap',
  },
  {
    id: 'slot:math:footnote',
    type: 'text',
    x: 128,
    y: 1318,
    w: 984,
    h: 36,
    maxChars: 70,
    maxLines: 2,
    overflow: 'clip',
  },
  {
    id: 'slot:final:headline',
    type: 'text',
    x: 160,
    y: 1468,
    w: 920,
    h: 74,
    maxChars: 120,
    maxLines: 2,
    overflow: 'wrap',
  },
  {
    id: 'slot:final:cta',
    type: 'cta',
    x: 490,
    y: 1566,
    w: 260,
    h: 48,
    maxChars: 22,
    maxLines: 1,
    overflow: 'ellipsis',
  },
];

export const LANDING_BASE_SLOTS_PORTRAIT: TemplateSlot[] = LANDING_BASE_SLOTS_PORTRAIT_SOURCE;

export const TEMPLATE_PAGE = LANDING_PAGE_PORTRAIT;


