import type { TemplateSlot } from '../types/template';
import { A4_BASE_HEIGHT, A4_BASE_WIDTH } from './templateEditor.ts';

/** Canonical slot geometry; pitch packs overlay patches on this baseline. */
export const LANDING_BASE_SLOTS: TemplateSlot[] = [
  {
    id: 'slot:hero:badge',
    type: 'pill',
    componentKind: 'statChip',
    x: 140,
    y: 76,
    w: 120,
    h: 44,
    maxChars: 16,
    maxLines: 1,
    overflow: 'ellipsis',
  },
  {
    id: 'slot:hero:headline',
    type: 'text',
    x: 140,
    y: 140,
    w: 740,
    h: 148,
    maxChars: 110,
    maxLines: 3,
    overflow: 'wrap',
  },
  {
    id: 'slot:hero:subheadline',
    type: 'text',
    x: 140,
    y: 304,
    w: 740,
    h: 96,
    maxChars: 190,
    maxLines: 3,
    overflow: 'wrap',
  },
  {
    id: 'slot:hero:cta:primary',
    type: 'cta',
    x: 140,
    y: 430,
    w: 188,
    h: 52,
    maxChars: 26,
    maxLines: 1,
    overflow: 'ellipsis',
  },
  {
    id: 'slot:hero:cta:secondary',
    type: 'cta',
    x: 348,
    y: 430,
    w: 188,
    h: 52,
    maxChars: 26,
    maxLines: 1,
    overflow: 'ellipsis',
  },
  { id: 'slot:hero:visual', type: 'box', x: 930, y: 110, w: 520, h: 380 },
  {
    id: 'slot:social:title',
    type: 'text',
    x: 140,
    y: 530,
    w: 420,
    h: 40,
    maxChars: 60,
    maxLines: 1,
    overflow: 'ellipsis',
  },
  { id: 'slot:logo:1', type: 'logo', x: 140, y: 582, w: 160, h: 56, maxChars: 18, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:logo:2', type: 'logo', x: 318, y: 582, w: 160, h: 56, maxChars: 18, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:logo:3', type: 'logo', x: 496, y: 582, w: 160, h: 56, maxChars: 18, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:logo:4', type: 'logo', x: 674, y: 582, w: 160, h: 56, maxChars: 18, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:logo:5', type: 'logo', x: 852, y: 582, w: 160, h: 56, maxChars: 18, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:logo:6', type: 'logo', x: 1030, y: 582, w: 160, h: 56, maxChars: 18, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:steps:pill:1', type: 'pill', x: 140, y: 672, w: 214, h: 54, maxChars: 26, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:steps:pill:2', type: 'pill', x: 444, y: 672, w: 214, h: 54, maxChars: 26, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:steps:pill:3', type: 'pill', x: 748, y: 672, w: 214, h: 54, maxChars: 26, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:steps:connector:1', type: 'connector', x: 356, y: 699, w: 84, h: 4 },
  { id: 'slot:steps:connector:2', type: 'connector', x: 660, y: 699, w: 84, h: 4 },
  {
    id: 'slot:steps:desc:1',
    type: 'text',
    x: 140,
    y: 735,
    w: 214,
    h: 52,
    maxChars: 62,
    maxLines: 2,
    overflow: 'wrap',
  },
  {
    id: 'slot:steps:desc:2',
    type: 'text',
    x: 444,
    y: 735,
    w: 214,
    h: 52,
    maxChars: 62,
    maxLines: 2,
    overflow: 'wrap',
  },
  {
    id: 'slot:steps:desc:3',
    type: 'text',
    x: 748,
    y: 735,
    w: 214,
    h: 52,
    maxChars: 62,
    maxLines: 2,
    overflow: 'wrap',
  },
  { id: 'slot:math:box', type: 'box', x: 990, y: 668, w: 460, h: 168 },
  {
    id: 'slot:math:title',
    type: 'text',
    x: 1030,
    y: 692,
    w: 380,
    h: 34,
    maxChars: 44,
    maxLines: 1,
    overflow: 'ellipsis',
  },
  {
    id: 'slot:math:formula',
    type: 'text',
    x: 1030,
    y: 726,
    w: 380,
    h: 46,
    maxChars: 90,
    maxLines: 2,
    overflow: 'wrap',
  },
  {
    id: 'slot:math:footnote',
    type: 'text',
    x: 1030,
    y: 774,
    w: 380,
    h: 38,
    maxChars: 100,
    maxLines: 2,
    overflow: 'clip',
  },
  {
    id: 'slot:final:headline',
    type: 'text',
    x: 140,
    y: 816,
    w: 760,
    h: 42,
    maxChars: 88,
    maxLines: 1,
    overflow: 'ellipsis',
  },
  {
    id: 'slot:final:cta',
    type: 'cta',
    x: 1220,
    y: 804,
    w: 228,
    h: 56,
    maxChars: 28,
    maxLines: 1,
    overflow: 'ellipsis',
  },
];

/** landing.v1 — landscape editorial layout tuned for 1280x1024 output. */
export const LANDING_PAGE_PORTRAIT = {
  width: A4_BASE_WIDTH,
  height: A4_BASE_HEIGHT,
} as const;

const LANDING_BASE_SLOTS_PORTRAIT_SOURCE: TemplateSlot[] = [
  {
    id: 'slot:hero:badge',
    type: 'pill',
    componentKind: 'statChip',
    x: 56,
    y: 104,
    w: 220,
    h: 36,
    maxChars: 28,
    maxLines: 1,
    overflow: 'ellipsis',
  },
  {
    id: 'slot:hero:headline',
    type: 'text',
    x: 56,
    y: 156,
    w: 704,
    h: 136,
    maxChars: 140,
    maxLines: 3,
    overflow: 'wrap',
  },
  {
    id: 'slot:hero:subheadline',
    type: 'text',
    x: 56,
    y: 300,
    w: 676,
    h: 88,
    maxChars: 220,
    maxLines: 3,
    overflow: 'wrap',
  },
  {
    id: 'slot:hero:cta:primary',
    type: 'cta',
    x: 56,
    y: 406,
    w: 224,
    h: 48,
    maxChars: 32,
    maxLines: 1,
    overflow: 'ellipsis',
  },
  {
    id: 'slot:hero:cta:secondary',
    type: 'cta',
    x: 298,
    y: 406,
    w: 180,
    h: 48,
    maxChars: 24,
    maxLines: 1,
    overflow: 'ellipsis',
  },
  { id: 'slot:hero:visual', type: 'box', componentKind: 'barChartPanel', x: 816, y: 104, w: 408, h: 374 },
  {
    id: 'slot:social:title',
    type: 'text',
    x: 508,
    y: 420,
    w: 104,
    h: 24,
    maxChars: 24,
    maxLines: 1,
    overflow: 'ellipsis',
  },
  { id: 'slot:logo:1', type: 'logo', x: 624, y: 410, w: 116, h: 38, maxChars: 16, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:logo:2', type: 'logo', x: 748, y: 410, w: 116, h: 38, maxChars: 16, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:logo:3', type: 'logo', x: 872, y: 410, w: 116, h: 38, maxChars: 16, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:logo:4', type: 'logo', componentKind: 'footerMeta', x: 872, y: 948, w: 108, h: 28, maxChars: 14, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:logo:5', type: 'logo', componentKind: 'footerMeta', x: 992, y: 948, w: 108, h: 28, maxChars: 14, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:logo:6', type: 'logo', componentKind: 'footerMeta', x: 1112, y: 948, w: 108, h: 28, maxChars: 14, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:steps:pill:1', type: 'pill', componentKind: 'topTab', x: 56, y: 536, w: 220, h: 44, maxChars: 30, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:steps:pill:2', type: 'pill', componentKind: 'topTab', x: 290, y: 536, w: 220, h: 44, maxChars: 30, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:steps:pill:3', type: 'pill', componentKind: 'topTab', x: 524, y: 536, w: 220, h: 44, maxChars: 30, maxLines: 1, overflow: 'ellipsis' },
  { id: 'slot:steps:connector:1', type: 'connector', x: 276, y: 558, w: 14, h: 2 },
  { id: 'slot:steps:connector:2', type: 'connector', x: 510, y: 558, w: 14, h: 2 },
  {
    id: 'slot:steps:desc:1',
    type: 'text',
    componentKind: 'infoListItem',
    x: 56,
    y: 590,
    w: 220,
    h: 118,
    maxChars: 90,
    maxLines: 4,
    overflow: 'wrap',
  },
  {
    id: 'slot:steps:desc:2',
    type: 'text',
    componentKind: 'infoListItem',
    x: 290,
    y: 590,
    w: 220,
    h: 118,
    maxChars: 90,
    maxLines: 4,
    overflow: 'wrap',
  },
  {
    id: 'slot:steps:desc:3',
    type: 'text',
    componentKind: 'infoListItem',
    x: 524,
    y: 590,
    w: 220,
    h: 118,
    maxChars: 90,
    maxLines: 4,
    overflow: 'wrap',
  },
  { id: 'slot:math:box', type: 'box', componentKind: 'quoteCard', x: 758, y: 536, w: 466, h: 284 },
  {
    id: 'slot:math:title',
    type: 'text',
    x: 790,
    y: 564,
    w: 402,
    h: 64,
    maxChars: 56,
    maxLines: 2,
    overflow: 'wrap',
  },
  {
    id: 'slot:math:formula',
    type: 'text',
    x: 790,
    y: 634,
    w: 402,
    h: 136,
    maxChars: 180,
    maxLines: 5,
    overflow: 'wrap',
  },
  {
    id: 'slot:math:footnote',
    type: 'text',
    x: 790,
    y: 776,
    w: 402,
    h: 34,
    maxChars: 70,
    maxLines: 1,
    overflow: 'clip',
  },
  {
    id: 'slot:final:headline',
    type: 'text',
    x: 56,
    y: 938,
    w: 760,
    h: 44,
    maxChars: 120,
    maxLines: 1,
    overflow: 'ellipsis',
  },
  {
    id: 'slot:final:cta',
    type: 'cta',
    x: 1030,
    y: 934,
    w: 194,
    h: 48,
    maxChars: 22,
    maxLines: 1,
    overflow: 'ellipsis',
  },
];

export const LANDING_BASE_SLOTS_PORTRAIT: TemplateSlot[] = LANDING_BASE_SLOTS_PORTRAIT_SOURCE;

export const TEMPLATE_PAGE = { width: 1600, height: 900 } as const;


