import type { TemplateSchema } from '../../types/template';

export const LANDING_TEMPLATE_V1: TemplateSchema = {
  schemaVersion: '1',
  templateId: 'landing.v1',
  page: { width: 1600, height: 900 },
  slots: [
    {
      id: 'slot:hero:badge',
      type: 'pill',
      x: 140,
      y: 76,
      w: 120,
      h: 44,
      maxChars: 16,
      maxLines: 1,
      overflow: 'ellipsis',
    },
    {
      id: 'slot:hero:headline',
      type: 'text',
      x: 140,
      y: 140,
      w: 740,
      h: 148,
      maxChars: 110,
      maxLines: 3,
      overflow: 'wrap',
    },
    {
      id: 'slot:hero:subheadline',
      type: 'text',
      x: 140,
      y: 304,
      w: 740,
      h: 96,
      maxChars: 190,
      maxLines: 3,
      overflow: 'wrap',
    },
    {
      id: 'slot:hero:cta:primary',
      type: 'cta',
      x: 140,
      y: 430,
      w: 188,
      h: 52,
      maxChars: 26,
      maxLines: 1,
      overflow: 'ellipsis',
    },
    {
      id: 'slot:hero:cta:secondary',
      type: 'cta',
      x: 348,
      y: 430,
      w: 188,
      h: 52,
      maxChars: 26,
      maxLines: 1,
      overflow: 'ellipsis',
    },
    { id: 'slot:hero:visual', type: 'box', x: 930, y: 110, w: 520, h: 380 },
    {
      id: 'slot:social:title',
      type: 'text',
      x: 140,
      y: 530,
      w: 420,
      h: 40,
      maxChars: 60,
      maxLines: 1,
      overflow: 'ellipsis',
    },
    { id: 'slot:logo:1', type: 'logo', x: 140, y: 582, w: 160, h: 56, maxChars: 18, maxLines: 1, overflow: 'ellipsis' },
    { id: 'slot:logo:2', type: 'logo', x: 318, y: 582, w: 160, h: 56, maxChars: 18, maxLines: 1, overflow: 'ellipsis' },
    { id: 'slot:logo:3', type: 'logo', x: 496, y: 582, w: 160, h: 56, maxChars: 18, maxLines: 1, overflow: 'ellipsis' },
    { id: 'slot:logo:4', type: 'logo', x: 674, y: 582, w: 160, h: 56, maxChars: 18, maxLines: 1, overflow: 'ellipsis' },
    { id: 'slot:logo:5', type: 'logo', x: 852, y: 582, w: 160, h: 56, maxChars: 18, maxLines: 1, overflow: 'ellipsis' },
    { id: 'slot:logo:6', type: 'logo', x: 1030, y: 582, w: 160, h: 56, maxChars: 18, maxLines: 1, overflow: 'ellipsis' },
    { id: 'slot:steps:pill:1', type: 'pill', x: 140, y: 672, w: 214, h: 54, maxChars: 26, maxLines: 1, overflow: 'ellipsis' },
    { id: 'slot:steps:pill:2', type: 'pill', x: 444, y: 672, w: 214, h: 54, maxChars: 26, maxLines: 1, overflow: 'ellipsis' },
    { id: 'slot:steps:pill:3', type: 'pill', x: 748, y: 672, w: 214, h: 54, maxChars: 26, maxLines: 1, overflow: 'ellipsis' },
    { id: 'slot:steps:connector:1', type: 'connector', x: 356, y: 699, w: 84, h: 4 },
    { id: 'slot:steps:connector:2', type: 'connector', x: 660, y: 699, w: 84, h: 4 },
    {
      id: 'slot:steps:desc:1',
      type: 'text',
      x: 140,
      y: 735,
      w: 214,
      h: 52,
      maxChars: 62,
      maxLines: 2,
      overflow: 'wrap',
    },
    {
      id: 'slot:steps:desc:2',
      type: 'text',
      x: 444,
      y: 735,
      w: 214,
      h: 52,
      maxChars: 62,
      maxLines: 2,
      overflow: 'wrap',
    },
    {
      id: 'slot:steps:desc:3',
      type: 'text',
      x: 748,
      y: 735,
      w: 214,
      h: 52,
      maxChars: 62,
      maxLines: 2,
      overflow: 'wrap',
    },
    { id: 'slot:math:box', type: 'box', x: 990, y: 668, w: 460, h: 168 },
    {
      id: 'slot:math:title',
      type: 'text',
      x: 1030,
      y: 692,
      w: 380,
      h: 34,
      maxChars: 44,
      maxLines: 1,
      overflow: 'ellipsis',
    },
    {
      id: 'slot:math:formula',
      type: 'text',
      x: 1030,
      y: 726,
      w: 380,
      h: 46,
      maxChars: 90,
      maxLines: 2,
      overflow: 'wrap',
    },
    {
      id: 'slot:math:footnote',
      type: 'text',
      x: 1030,
      y: 774,
      w: 380,
      h: 38,
      maxChars: 100,
      maxLines: 2,
      overflow: 'clip',
    },
    {
      id: 'slot:final:headline',
      type: 'text',
      x: 140,
      y: 816,
      w: 760,
      h: 42,
      maxChars: 88,
      maxLines: 1,
      overflow: 'ellipsis',
    },
    {
      id: 'slot:final:cta',
      type: 'cta',
      x: 1220,
      y: 804,
      w: 228,
      h: 56,
      maxChars: 28,
      maxLines: 1,
      overflow: 'ellipsis',
    },
  ],
};
